version: '3.7'

services:
  
  mongodb:
    ports:
      - "27017:27017"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    ports:
      - "6379:6379"

  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

  logstash:
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    ports:
      - "9600"
      - "5000"

  kibana:
    ports:
      - 51510:5601

networks:
  default:
    external:
      name: dev-net  